### ISSUE TITLE
Typo: Celcius -> Celsius

### ISSUE THREAD

**Issue by j0bro** [minimosd-ng/minimosd-ng#1]
Saw it in the first screenshot in the first post of the minimosd-ng thread on RCG, found the String "Celcius" to be in startup.c:61 

Also used in at least one constant (MAX7456_FONT_CELCIUS) and method name (CELCIUS2FAHR) in temperature.c

**Comment by ljalves** [comment]
Thanks for noticing!
Fixed in 1ca1faf2c724b93b6cc839fcc3685163506df2d0

**Comment by j0bro** [comment]
np, happy to help. I will definitely go and test your firmware, it looks very promising!
